name: Actualizar noticias cada d칤a

on:
  schedule:
    - cron: '0 6 * * *'  # todos los d칤as a las 6:00 UTC (8:00 en Espa침a)
  workflow_dispatch:     # permite ejecutarlo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install feedparser

      - name: Ejecutar script de generaci칩n de noticias
        run: python generar_noticias.py

      - name: Hacer commit y push si hay cambios
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Actualizaci칩n autom치tica de noticias 游닗" || echo "Sin cambios"
          git push
